services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports: ["5672:5672", "15672:15672"]
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [cashflow-network]
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ALLOW_LOOPBACK_USERS: "guest"

  launch-api:
    container_name: launch-api
    build:
      context: ./src
      dockerfile: Cashflow.Launch/Cashflow.Launch.API/Dockerfile
    ports: ["8001:8080"]
    depends_on: 
      rabbitmq:
        condition: service_healthy
    networks: [cashflow-network]
    volumes:
      - ./data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/launch.db

  consolidated-api:
    container_name: consolidated-api
    build:
      context: ./src
      dockerfile: Cashflow.Consolidated/Cashflow.Consolidated.API/Dockerfile
    ports: ["8002:8080"]
    depends_on: [rabbitmq]
    networks: [cashflow-network]
    volumes:
      - ./data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/consolidated.db

networks:
  cashflow-network:
    driver: bridge
